image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.3.2:GoBUk/Z8vRkFzT/mkYNBhQ==
    - ms-vscode.csharp@1.21.8:b295AK/AkVs7Pl/asBNDzQ==
    - kube.theme-kay@1.0.2:RNWWHFExFoXnYuXUeUXs+Q==