image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - Ionide.Ionide-fsharp@4.3.2:GoBUk/Z8vRkFzT/mkYNBhQ==
    - kube.theme-kay@1.0.2:RNWWHFExFoXnYuXUeUXs+Q==
    - k--kato.intellij-idea-keybindings@0.2.37:vz3hpwf8WGtALEI7zq/EXA==
