version: '3.1'

services:
  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./__data/mongodb:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
