#!/usr/bin/env python3
"""Refresh the local Telegram Bot API reference from its official source."""

from __future__ import annotations

from datetime import UTC, datetime
from html import unescape
from html.parser import HTMLParser
from pathlib import Path
import re
from urllib.request import Request, urlopen


SOURCE_URL = "https://core.telegram.org/bots/api"
SKILL_DIR = Path(__file__).resolve().parents[1]
REFERENCES_DIR = SKILL_DIR / "references"


class MarkdownParser(HTMLParser):
    """Small HTML-to-Markdown converter for the structured Bot API reference."""

    ignored_tags = {"script", "style", "svg"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self.ignored_depth = 0
        self.pre_depth = 0
        self.inline_code_depth = 0
        self.link_hrefs: list[str | None] = []
        self.table_cells: list[str] | None = None
        self.current_cell: list[str] | None = None

    def text(self, value: str) -> None:
        if self.current_cell is not None:
            self.current_cell.append(value)
        else:
            self.parts.append(value)

    def newline(self, count: int = 1) -> None:
        if self.current_cell is None:
            self.parts.append("\n" * count)

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in self.ignored_tags:
            self.ignored_depth += 1
            return
        if self.ignored_depth:
            return

        attributes = dict(attrs)
        if tag in {"h1", "h2", "h3", "h4", "h5", "h6"}:
            self.newline(2)
            self.parts.append("#" * int(tag[1]) + " ")
        elif tag in {"p", "div", "section", "article", "blockquote"}:
            self.newline(2)
        elif tag == "br":
            self.newline()
        elif tag in {"ul", "ol"}:
            self.newline()
        elif tag == "li":
            self.newline()
            self.parts.append("- ")
        elif tag == "pre":
            self.newline(2)
            self.parts.append("```\n")
            self.pre_depth += 1
        elif tag == "code" and not self.pre_depth:
            self.text("`")
            self.inline_code_depth += 1
        elif tag == "a":
            self.link_hrefs.append(attributes.get("href"))
        elif tag == "table":
            self.newline(2)
        elif tag == "tr":
            self.table_cells = []
        elif tag in {"th", "td"}:
            self.current_cell = []

    def handle_endtag(self, tag: str) -> None:
        if tag in self.ignored_tags:
            self.ignored_depth -= 1
            return
        if self.ignored_depth:
            return

        if tag in {"h1", "h2", "h3", "h4", "h5", "h6", "p", "div", "section", "article", "blockquote"}:
            self.newline(2)
        elif tag == "pre":
            self.newline()
            self.parts.append("```\n")
            self.pre_depth -= 1
        elif tag == "code" and self.inline_code_depth:
            self.text("`")
            self.inline_code_depth -= 1
        elif tag == "a" and self.link_hrefs:
            href = self.link_hrefs.pop()
            if href and not href.startswith("#"):
                self.text(f" ({href})")
        elif tag in {"th", "td"} and self.current_cell is not None:
            cell = " ".join("".join(self.current_cell).split()).replace("|", "\\|")
            if self.table_cells is not None:
                self.table_cells.append(cell)
            self.current_cell = None
        elif tag == "tr" and self.table_cells:
            self.parts.append("| " + " | ".join(self.table_cells) + " |\n")
            self.table_cells = None

    def handle_data(self, data: str) -> None:
        if not self.ignored_depth:
            self.text(data)

    def markdown(self) -> str:
        text = unescape("".join(self.parts)).replace("\xa0", " ")
        text = re.sub(r"[ \t]+\n", "\n", text)
        text = re.sub(r"\n{3,}", "\n\n", text)
        return text.strip() + "\n"


def heading_index(lines: list[str], title: str) -> int:
    for index, line in enumerate(lines):
        if line.lstrip("#").strip().casefold() == title.casefold():
            return index
    raise ValueError(f"Could not find the {title!r} section")


def write_reference(name: str, body: str, version: str) -> None:
    title = name.replace("_", " ").title()
    timestamp = datetime.now(UTC).date().isoformat()
    header = (
        "<!-- Generated by scripts/update_reference.py. Do not edit manually. -->\n"
        f"# Telegram Bot API: {title}\n\n"
        f"Source: {SOURCE_URL}\n\n"
        f"Bot API version: {version}\n\n"
        f"Snapshot date: {timestamp}\n\n"
    )
    (REFERENCES_DIR / f"{name}.md").write_text(header + body, encoding="utf-8")


def main() -> None:
    request = Request(SOURCE_URL, headers={"User-Agent": "spectator-telegram-bot-api-snapshot"})
    with urlopen(request, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"Telegram Bot API returned HTTP {response.status}")
        html = response.read().decode("utf-8")

    parser = MarkdownParser()
    parser.feed(html)
    lines = parser.markdown().splitlines(keepends=True)
    updates_start = heading_index(lines, "Getting updates")
    update_type_start = heading_index(lines, "Update")
    get_updates_start = heading_index(lines, "getUpdates")
    methods_start = heading_index(lines, "Available methods")
    types_start = heading_index(lines, "Available types")
    if not updates_start < update_type_start < get_updates_start < types_start < methods_start:
        raise ValueError("The Bot API sections are not in the expected order")

    markdown = "".join(lines)
    version_match = re.search(r"Bot API\s+(\d+(?:\.\d+)*)", markdown)
    if version_match is None:
        raise ValueError("Could not determine the Bot API version")

    overview = "".join(lines[:updates_start]).strip() + "\n"
    types = (
        "".join(lines[update_type_start:get_updates_start])
        + "\n"
        + "".join(lines[types_start:methods_start])
    ).strip() + "\n"
    methods = (
        "".join(lines[get_updates_start:types_start])
        + "\n"
        + "".join(lines[methods_start:])
    ).strip() + "\n"
    if "sendMessage" not in methods or "getUpdates" not in methods or "Update" not in types:
        raise ValueError("The extracted reference is missing core Bot API entries")
    if re.search(r"^`{1,2}$|^`{4,}$", markdown, flags=re.MULTILINE):
        raise ValueError("The extracted reference contains malformed inline code")

    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    version = version_match.group(1)
    write_reference("overview", overview, version)
    write_reference("methods", methods, version)
    write_reference("types", types, version)
    print(f"Updated Telegram Bot API {version} reference in {REFERENCES_DIR}")


if __name__ == "__main__":
    main()
