name = "spectator"
main = "bin/src/main.js"
compatibility_date = "2026-08-24"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd .. && make build"
watch_dir = ["../src"]

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "TASKS"
database_name = "spectator-tasks"
database_id = "97011597-adcf-497c-927a-1df93724f7e6"
migrations_dir = "../migrations"
